### ISSUE TITLE
Error in response

### ISSUE THREAD

**Issue by JayUltra** [k4l1sh/alexa-gpt#16]
![image](https://github.com/k4l1sh/alexa-gpt/assets/147024045/0ffa5306-e856-4135-a034-09ead4628872)
Hello sir, 
i am getting this as my response

Error 429: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

I am currently using a free tier account in openai. do i need to upgrade. I am only a hobbyist. which subscription would i need to add sir
I have also shared the screenshot
thanks!

**Comment by k4l1sh** [comment]
Yes, this is due to the free tier rate limits
https://platform.openai.com/docs/guides/rate-limits/free-tier-rate-limits?context=tier-free
If you want to use more than 3 rpm you should update to tier 1

**Comment by JayUltra** [comment]
alright sir, gpt 3.5 turbo would do right
