### ISSUE TITLE
Help not working, not published

### ISSUE THREAD

**Issue by Blueboys74** [k4l1sh/alexa-gpt#18]
When trying to publish the Skill it is getting rejected :
The help prompt must end with a question for users or prompt the user to speak and leave the session open to receive a response. 
![2024-05-18_19h57_28](https://github.com/k4l1sh/alexa-gpt/assets/170202093/3e8039ac-3920-42ae-9d7c-9523b2bb7ade)

Not sure what the problem is as i dont see a coding issue.
I am inexperienced in coding so take it easy on me :)

**Comment by k4l1sh** [comment]
"help" is a reserved word of alexa to activate Help Intent Handler.
In this code, the help intent handler is not added, only the stop, cancel, gpt and activate intent handlers.
Your chat should work fine if you don't activate the help intent.
Maybe in the future we could add a help intent to avoid this exception error
![image](https://i.imgur.com/7VkdP5L.png)

**Comment by Blueboys74** [comment]
The problem is i do need to activate it and it seems not to work according the decline mail i got while publishing it.
What line should be the help intent?

**Comment by k4l1sh** [comment]
You don't need to publish the skill or promote it to live to make it work, you only need to "Build" and "Deploy".
If you go to the Test section and enable it to "Development", as indicated in [the last step of the tutorial](https://github.com/k4l1sh/alexa-gpt?tab=readme-ov-file#13), you should be able to talk with your alexa, if your alexa is using the same account that you created the skill with.

**Comment by Blueboys74** [comment]
Hello k4l1sh, thank you for that, i was not able to see the skill in the skill center so i thought it was not working on my Alexa. Seems to be working now. thank you very much for the help
